import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import Link from "next/link";
import "./globals.css";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
      >
        <header className="border-b border-slate-800">
          <nav className="mx-auto flex max-w-4xl items-center justify-between px-4 py-4">
            <Link href="/" className="font-semibold">
              Dylan Val
            </Link>
            <div className="flex gap-4 text-sm">
              <Link href="/about">About</Link>
              <Link href="/experience">Experience</Link>
              <Link href="/gallery">Gallery</Link>
              <Link href="/mountaineering">Mountaineering</Link>
              <Link href="/contact">Contact</Link>
            </div>
          </nav>
        </header>
        {children}
      </body>
    </html>
  );
}
